name: Laravel CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
      - name: Install deps
        run: composer install --no-progress --no-interaction
      - name: App key
        run: php artisan key:generate --no-interaction
      - name: Run tests
        run: php artisan test --no-interaction
